// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type conntrackListenInfo struct {
	Pid  uint32
	Comm [16]int8
}

type conntrackListenKey struct {
	Port     uint16
	_        [2]byte
	NetnsIno uint32
}

// loadConntrack returns the embedded CollectionSpec for conntrack.
func loadConntrack() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConntrackBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load conntrack: %w", err)
	}

	return spec, err
}

// loadConntrackObjects loads conntrack and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*conntrackObjects
//	*conntrackPrograms
//	*conntrackMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConntrackObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConntrack()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// conntrackSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackSpecs struct {
	conntrackProgramSpecs
	conntrackMapSpecs
}

// conntrackSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackProgramSpecs struct {
	InetCskAccept     *ebpf.ProgramSpec `ebpf:"inet_csk_accept"`
	InetCskListenStop *ebpf.ProgramSpec `ebpf:"inet_csk_listen_stop"`
	InetListen        *ebpf.ProgramSpec `ebpf:"inet_listen"`
	TcpV4ConnectEntry *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_entry"`
	TcpV4ConnectExit  *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_exit"`
	UdpQueueRcvSkb    *ebpf.ProgramSpec `ebpf:"udp_queue_rcv_skb"`
	UdpSendmsg        *ebpf.ProgramSpec `ebpf:"udp_sendmsg"`
}

// conntrackMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	ListenPorts     *ebpf.MapSpec `ebpf:"listen_ports"`
	TcpConnectSocks *ebpf.MapSpec `ebpf:"tcp_connect_socks"`
}

// conntrackObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackObjects struct {
	conntrackPrograms
	conntrackMaps
}

func (o *conntrackObjects) Close() error {
	return _ConntrackClose(
		&o.conntrackPrograms,
		&o.conntrackMaps,
	)
}

// conntrackMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	ListenPorts     *ebpf.Map `ebpf:"listen_ports"`
	TcpConnectSocks *ebpf.Map `ebpf:"tcp_connect_socks"`
}

func (m *conntrackMaps) Close() error {
	return _ConntrackClose(
		m.Events,
		m.ListenPorts,
		m.TcpConnectSocks,
	)
}

// conntrackPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackPrograms struct {
	InetCskAccept     *ebpf.Program `ebpf:"inet_csk_accept"`
	InetCskListenStop *ebpf.Program `ebpf:"inet_csk_listen_stop"`
	InetListen        *ebpf.Program `ebpf:"inet_listen"`
	TcpV4ConnectEntry *ebpf.Program `ebpf:"tcp_v4_connect_entry"`
	TcpV4ConnectExit  *ebpf.Program `ebpf:"tcp_v4_connect_exit"`
	UdpQueueRcvSkb    *ebpf.Program `ebpf:"udp_queue_rcv_skb"`
	UdpSendmsg        *ebpf.Program `ebpf:"udp_sendmsg"`
}

func (p *conntrackPrograms) Close() error {
	return _ConntrackClose(
		p.InetCskAccept,
		p.InetCskListenStop,
		p.InetListen,
		p.TcpV4ConnectEntry,
		p.TcpV4ConnectExit,
		p.UdpQueueRcvSkb,
		p.UdpSendmsg,
	)
}

func _ConntrackClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed conntrack_x86_bpfel.o
var _ConntrackBytes []byte
