server {
    listen 80;
    # CHANGE NAME
    server_name srv-estc;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    # CHANGE NAME
    server_name srv-estc;
    # CHANGE SSL PATH
    ssl_certificate     /etc/nginx/certs/cert.crt;
    ssl_certificate_key /etc/nginx/private/cert.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location /map/ {
	 default_type image/svg+xml;
	# CHANGE TOKEN 
         if ($arg_token != "TOKEN_TOKEN") {
             return 403;
         }
    
         proxy_pass http://map-server:8085;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
    
         add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }

    location / {
        auth_basic "Restricted Access: Network Map";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://map-server:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_hide_header Cache-Control;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }
}
